### PR TITLE
Freedesktop.org files for desktop integration.

### PR DESCRIPTION
**Pull request by MrSVCD**
One png icon and a .desktop file for desktop integration on Linux.

### CODE REVIEW

**Comment by 8bitbubsy** [comment]
That LICENSE file is a bitmisleading, makes it look like you're behind compiled Linux binaries of the PT2 clone...

**Comment by MrSVCD** [comment]
Ok, changed the name of the license file.

**Comment by 8bitbubsy** [comment]
I was referring to the content of the file. It doesn't state what the license is for, so it may seem like it's for the PT2 clone itself, which is misleading. Can you write on top of license file that it's for the icon and .desktop file, or is that not suitable for .LICENSE files?

**Comment by MrSVCD** [comment]
I have now changed some names to better reflect what they actually do.
The folder is now called "Freedesktop.org Resources" and the License file is again named LICENSE since that is, to my knowledge, the de facto way to say that all files in the folder and deeper in the folder hierarchy is under the license in the file "LICENSE" until another license file is encountered.

**Comment by 8bitbubsy** [comment]
> I have now changed some names to better reflect what they actually do. The folder is now called "Freedesktop.org Resources" and the License file is again named LICENSE since that is, to my knowledge, the de facto way to say that all files in the folder and deeper in the folder hierarchy is under the license in the file "LICENSE" until another license file is encountered.

I see! I'll merge the stuff now.

**Pull request merged**
